version: 0.1
component: build
timeoutInSeconds: 600
runAs: root
shell: bash
env:
  variables:
    "major_version" : "1.1"
  exportedVariables:
    - major_version

steps:
  - type: Command
    name: "compose install"
    command: |
      yum install -y yum-utils
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      yum update
      yum install docker-compose-plugin
  - type: Command
    name: "compose version"
    command: |
      docker compose version
  - type: Command
    name: "ls"
    command: |
      ls
  # - type: Command
  #   name: "Dockerize"
  #   command: |
  #     docker build -t docktest .
  # - type: Command
  #   name: "Save"
  #   command: |
  #     docker save docktest -o docktest.tar
  #     pwd
  #     ls -lart
  # - type: Command
  #   name: "SaveResult"
  #   command: |
  #     ls >> dockImagesResult.txt
  
#   - type: Command
#     name: "SaveResult"
#     command: |
#       export major_version=1.2
# outputArtifacts:
#   - name: docktest
#     type: BINARY
#     location: docktest.tar
#   - name: docktestdocker
#     type: DOCKER_IMAGE
#     location: docktest
